name: Francesco Mari
description: "Personal blog"
meta_description: "Personal blog of Francesco Mari"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15

url: 'https://francescomari.github.io'
author: 'Francesco Mari'
