name: Francesco Mari
description: "I smell code"
meta_description: "Personal blog of Francesco Mari"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

url: 'https://francescomari.github.io'
author: 'Francesco Mari'
