name: Francesco Mari
description: "Personal blog"
meta_description: "Personal blog of Francesco Mari"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
exclude: ["Gemfile", "Gemfile.lock", "CNAME"]

url: 'https://francescomari.github.io'
author: 'Francesco Mari'
